name: Build docker images
concurrency:
  group: "${{github.workflow}}-${{github.ref}}"
  cancel-in-progress: true
on:
  workflow_dispatch:
  schedule:
    - cron: "0 5 * * 3" # At 05:00 on Wednesday # https://crontab.guru/#0_5_*_*_3
  push:
    branches:
      - master
    tags:
      - "*.*.*"
  pull_request:
    types: [opened, synchronize]
    branches:
      - "*"

jobs:
  # These jobs use Buildx layer caching
  docker_build:
    name: Build

    strategy:
      fail-fast: false
      matrix:
        platform:
          - x86-mingw32
          - x64-mingw-ucrt
          - x64-mingw32
          - x86-linux
          - x86_64-linux

    runs-on: ubuntu-latest
    env:
      PLATFORM: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.3"
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically

      - name: Build libusb.gem
        run: |
          bundle exec rake gem:native:${PLATFORM}

      - name: Upload binary gem
        uses: actions/upload-artifact@v4
        with:
          name: gem-${{ matrix.platform }}
          path: pkg/*-*-*.gem

      - if: matrix.platform == 'jruby'
        name: Upload source gem
        uses: actions/upload-artifact@v4
        with:
          name: gem-ruby
          path: pkg/*-?.?.?.gem

  job_test_native:
    name: Bin (${{matrix.ruby}}, ${{matrix.os}}, ${{matrix.platform}})
    needs: docker_build
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows
            ruby: "2.5"
            platform: x64-mingw32
          - os: windows
            ruby: "3.3"
            platform: x64-mingw-ucrt
          - os: ubuntu
            ruby: "2.5"
            platform: x86_64-linux
          - os: ubuntu
            ruby: "3.3"
            platform: x86_64-linux

    runs-on: ${{ matrix.os }}-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - run: ruby --version
      - name: Download gem-${{matrix.platform}}
        uses: actions/download-artifact@v4
        with:
          name: gem-${{ matrix.platform }}
      - name: Install gem-${{matrix.platform}}
        run: gem install *.gem --verbose
      - name: bundle install
        run: bundle install
      - name: Generate Gemfile_libusb_gem to ensure the installed gem is used
        run: bundle exec rake gemfile_libusb_gem
      - name: Run tests
        env:
          BUNDLE_GEMFILE: Gemfile_libusb_gem
        run: |
          bundle exec rake ci

  # These jobs use Buildx layer caching
  source_gem:
    name: Source gem

    strategy:
      fail-fast: false

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.3"
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically

      - name: Build libusb.gem
        run: |
          bundle exec rake gem

      - name: Upload binary gem
        uses: actions/upload-artifact@v4
        with:
          name: gem-ruby
          path: pkg/*.gem

  job_test_source:
    name: Src (${{matrix.ruby}}, ${{matrix.os}})
    needs: source_gem
    strategy:
      fail-fast: false
      matrix:
        os:
          - windows
          - ubuntu
          - macos
        ruby:
          - "3.3"
          - "2.5"
          - "head"
          - "jruby"
          - "truffleruby"
        exclude:
          - os: windows
            ruby: "truffleruby"

    runs-on: ${{ matrix.os }}-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - run: ruby --version
      - name: Download gem
        uses: actions/download-artifact@v4
        with:
          name: gem-ruby
      - name: Install gem
        run: gem install *.gem --verbose
      - name: bundle install
        run: bundle install
      - name: Generate Gemfile_libusb_gem to ensure the installed gem is used
        run: bundle exec rake gemfile_libusb_gem
      - name: Run tests
        env:
          BUNDLE_GEMFILE: Gemfile_libusb_gem
        run: |
          bundle exec rake ci
