name: Build docker images
concurrency:
  group: "${{github.workflow}}-${{github.ref}}"
  cancel-in-progress: true
on:
  workflow_dispatch:
  schedule:
    - cron: "0 5 * * 3" # At 05:00 on Wednesday # https://crontab.guru/#0_5_*_*_3
  push:
    branches:
      - master
    tags:
      - "*.*.*"
  pull_request:
    types: [opened, synchronize]
    branches:
      - "*"

jobs:
  # These jobs use Buildx layer caching
  docker_build:
    name: Build

    strategy:
      fail-fast: false
      matrix:
        platform:
          - x86-mingw32
          - x64-mingw-ucrt
          - x64-mingw32
          - x86-linux
          - x86_64-linux
          - x86_64-darwin
          - arm64-darwin
          - arm-linux
          - aarch64-linux
          - jruby
          - truffleruby

    runs-on: ubuntu-latest
    env:
      PLATFORM: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v3

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.2"
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically

      - name: Build libusb.gem
        run: |
          bundle exec rake gem:native:${PLATFORM}

      - name: Upload binary gem
        uses: actions/upload-artifact@v3
        with:
          name: gem-${{ matrix.platform }}
          path: pkg/*-*-*.gem

      - if: matrix.platform == 'jruby'
        name: Upload source gem
        uses: actions/upload-artifact@v3
        with:
          name: gem-ruby
          path: pkg/*-?.?.?.gem

  job_test_native:
    name: Test (${{matrix.ruby}}, ${{matrix.platform}})
    needs: docker_build
    strategy:
      fail-fast: false
      matrix:
        os:
          - windows
          - macos
          - ubuntu
        ruby:
          - "3.2"
          - "2.4"
        include:
          - os: windows
            platform: x64-mingw32
          - os: macos
            platform: x86_64-darwin
          - os: ubuntu
            platform: x86_64-linux
          - os: ubuntu
            platform: ruby
          - os: ubuntu
            ruby: jruby-head
            platform: jruby
          - os: windows
            ruby: "3.2"
            platform: x64-mingw-ucrt
        exclude:
          - os: windows
            ruby: "3.2"

    runs-on: ${{ matrix.os }}-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      - run: ruby --version
      - name: Download gem-${{matrix.platform}}
        uses: actions/download-artifact@v3
        with:
          name: gem-${{ matrix.platform }}
      - name: Install gem-${{matrix.platform}}
        run: gem install --local *.gem --verbose
      - name: Run tests
        run: |
          bundle exec rake test
